controller_list:
  - name: fake_crane_x7_arm_controller
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
      - arm_joint6
      - arm_joint7
  - name: fake_crane_x7_hand_controller
    joints:
      - hand_joint1